# Generated by Django 4.2.4 on 2023-09-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='synonyms',
        ),
        migrations.AddField(
            model_name='word',
            name='synonyms',
            field=models.ManyToManyField(blank=True, to='users.word'),
        ),
    ]
