# Generated by Django 4.2.4 on 2023-09-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_word_synonyms_word_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='translation',
            field=models.TextField(default='', max_length=100),
        ),
    ]
